### ISSUE TITLE
UX/UI TWEAK SUGGESTION

### ISSUE THREAD

**Issue by JuniorGarciaRodriguez** [romans-adi/portfolio-00#7]
# PEER-TO-PEER CODE REVIEW FEEDBACK

- Kindly consider adjusting the behavior of the [text field animation](https://github.com/romans-adi/portfolio-00/blob/09be18bd2cdf835c111323fa6b52f73d51691c61/assets/css/styles.css#L1131) for a better user experience, and consider including a media query for a reduced motion to disable it as it might be unpleasant for some users.

- Consider removing the `!important` flag unless it's necessary for your code to work properly to follow best practices

- Consider switching the border style of your button to transparent and see how it changes. It will improve the accessibility of the page for users with high contrast mode on

**Comment by romans-adi** [comment]
Thank you for the suggestions! I appreciate it. :blush:

- [x] Animation was removed due to a bad user experience.  :pencil2:
- [x] `!important` flag was removed from one line where it was not needed. For two other lines, however, it is still important for the proper work in different browsers.  :pencil2:
- [x] Transparent borders added to all buttons. :pencil2:
